#ifndef _CONFIG

#define _CONFIG

#include <Arduino.h>
#include "wiring_private.h" // pinPeripheral() function


// Set SERCOM peripherals
void configSerialPins() {
    pinPeripheral(5, PIO_SERCOM);

}


// Define GPIOs
#define GPIO_1_IO 42
#define GPIO_2_IO SWIO
#define GPIO_3_IO SWCLK

// Define Triggers
#define TRIG_4_0 A1
#define TRIG_1_0 8
#define TRIG_0_0 4

// Define LED Triggers
#define LED_TRIG1 12
#define LED_TRIG2 11
#define LED_TRIG3 10
#define LED_TRIG4 7

// Define Trigger pins
#define HIGH_MAG_CAM_TRIG GPIO_2_IO
#define LOW_MAG_CAM_TRIG GPIO_3_IO
#define HIGH_MAG_STROBE_TRIG TRIG_0_0
#define LOW_MAG_STROBE_TRIG TRIG_4_0
#define FLASH_TYPE_PIN TRIG_1_0

// Define dimming pins
#define DIMMING_CS 13

// Define power supply controls
#define LASER_ENABLE 2
#define CAMERA_POWER 6

#define DEBUGPORT Serial
#define HWPORT0 Serial0
#define HWPORT1 Serial

#define UI1 HWPORT0
#define JETSONPORT HWPORT1
#define RBRPORT HWPORT3

// Define Config Settings
#define LOGINT "LOGINT"
#define POLLFREQ "POLLFREQ"
#define DEPTHCHECKINTERVAL "DEPTHCHECKINTERVAL"
#define DEPTHTHRESHOLD "DEPTHTHRESHOLD"
#define LOCALECHO "LOCALECHO"
#define CMDTIMEOUT "CMDTIMEOUT"
#define HWPORT0BAUD "HWPORT0BAUD"
#define HWPORT1BAUD "HWPORT1BAUD"
#define HWPORT2BAUD "HWPORT2BAUD"
#define HWPORT3BAUD "HWPORT3BAUD"
#define STROBEDELAY "STROBEDELAY"
#define FRAMERATE "FRAMERATE"
#define TRIGWIDTH "TRIGWIDTH"
#define LOWMAGCOLORFLASH "LOWMAGCOLORFLASH"
#define LOWMAGREDFLASH "LOWMAGREDFLASH"
#define HIGHMAGCOLORFLASH "HIGHMAGCOLORFLASH"
#define HIGHMAGREDFLASH "HIGHMAGREDFLASH"
#define FLASHTYPE "FLASHTYPE"
#define PROFILEMODE "PROFILEMODE"
#define LOWVOLTAGE "LOWVOLTAGE"
#define STANDBY "STANDBY"
#define CHECKHOURLY "CHECKHOURLY"
#define STARTUPTIME "STARTUPTIME"
#define WATCHDOG "WATCHDOG"
#define CAMGUARD "CAMGUARD"
#define TEMPLIMIT "TEMPLIMIT"
#define HUMLIMIT "HUMLIMIT"
#define MAXSHUTDOWNTIME "MAXSHUTDOWNTIME"
#define CHECKINTERVAL "CHECKINTERVAL"
#define MINDEPTH "MINDEPTH"
#define MAXDEPTH "MAXDEPTH"
#define ECHORBR "ECHORBR"
#define USERBRCLOCK "USERBRCLOCK"
#define CTDTYPE "CTDTYPE"

// Define Commands
#define CFG "CFG"
#define PORTPASS "PORTPASS"
#define SETTIME "SETTIME"
#define WRITECONFIG "WRITECONFIG"
#define READCONFIG "READCONFIG"
#define CAMERAON "CAMERAON"
#define CAMERAOFF "CAMERAOFF"
#define SHUTDOWNJETSON "SHUTDOWNJETSON"
#define NEWEVENT "NEWEVENT"
#define PRINTEVENTS "PRINTEVENTS"
#define CLEAREVENTS "CLEAREVENTS"
#define LEDSON  "LEDSON"
#define LEDSOFF "LEDSOFF"


#endif